CREATE TABLE IF NOT EXISTS streams(
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    version INTEGER DEFAULT(-1) NOT NULL,
    position INTEGER DEFAULT(-1) NOT NULL,
    max_age INTEGER DEFAULT(NULL),
    max_count INTEGER DEFAULT(NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS streams_name_key ON streams (name);
